AnimalShelter.Solution/AnimalShelter/Models/Animal.cs
using System;
using System.Collections.Generic;

namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public DateTime DateAdmitted { get; set; }
    public string AnimalType { get; set; }
    public string Breed { get; set; }
  }

  public enum AnimalType
  {
    cat,
    dog,
    critter,
    other    
  }
}

AnimalShelter.Solution/AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter.Solution/AnimalShelter/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {

    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index(string sortBy)
    {
      List<Animal> sortedBy = _db.Animals.ToList();

      if (sortBy == "byName")
      {
        sortedBy = _db.Animals.OrderBy(animals => animals.Name).ToList();
      }
      else if (sortBy == "byBreed")
      {
        sortedBy = _db.Animals.OrderBy(animals => animals.Breed).ToList();
      }
      else if (sortBy == "byType")
      {
        sortedBy = _db.Animals.OrderBy(animals => animals.AnimalType).ToList();
      }
      else if (sortBy == "byDateAdmitted")
      {
        sortedBy = _db.Animals.OrderBy(animals => animals.DateAdmitted).ToList();
      }

      Dictionary<string, List<Animal>> model = new Dictionary<string, List<Animal>> {};
      model.Add("sortBy", sortedBy);
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal model = _db.Animals.FirstOrDefault(animals => animals.AnimalId == id);
      return View(model);
    }

  }
}

AnimalShelter.Solution/AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller
  {

    public ActionResult Index()
    {
      return View();
    }

  }
}

AnimalShelter.Solution/AnimalShelter/Views/Animals/Create.cshtml
@{
  ViewBag.Title = "Add an animal";
  Layout = "_Layout";
}

@using AnimalShelter.Models
@model AnimalShelter.Models.Animal

<h4>Add a new animal</h4>
<div class="form">
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Gender, "Male")
    @Html.RadioButton("Gender","M")
    @Html.LabelFor(model => model.Gender, "Female")  
    @Html.RadioButton("Gender","F")  
    <br>
    @Html.LabelFor(model => model.DateAdmitted, "Date Admitted")
    @Html.TextBoxFor(model => model.DateAdmitted, new { @type="date" })
    <br>
    @Html.LabelFor(model => model.AnimalType, "Type of Animal")
    @Html.DropDownListFor(model => model.AnimalType, new SelectList(Enum.GetValues(typeof(AnimalType))), "Select Type")
    <br>
    @Html.LabelFor(model => model.Breed)
    @Html.TextBoxFor(model => model.Breed)
    <br>
    <input type="submit" value="Add new animal" />
  }
</div>

<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter.Solution/AnimalShelter/Views/Animals/Details.cshtml
@{
    Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if (Model.Gender == "F")
{
    <p>@Html.DisplayNameFor(model => model.Gender): Female</p>
}

@if (Model.Gender == "M")
{
    <p>@Html.DisplayNameFor(model => model.Gender): Male</p>
}

<p>Date Admitted: @Html.DisplayFor(model => model.DateAdmitted.Month)/@Html.DisplayFor(model => model.DateAdmitted.Day)/@Html.DisplayFor(model => model.DateAdmitted.Year)</p>

<p>Type of Animal: @Html.DisplayFor(model => model.AnimalType)</p>

<p>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)</p>

<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter.Solution/AnimalShelter/Views/Animals/Index.cshtml
@{
  ViewBag.Title = "All animals";
  Layout = "_Layout";
}

@using AnimalShelter.Models;
@model Dictionary<string, List<Animal>>;
@* @model List<AnimalShelter.Models.Animal>; *@

<h1>Animals in our Shelter</h1>

@if (Model["sortBy"].Count == 0)
{
  <h4>There are currently no animals at the shelter.</h4>
}
else
{
  <p>@Html.ActionLink("Sort By Name", "Index", new { sortBy = "byName" }) | @Html.ActionLink("Sort By Breed", "Index", new { sortBy = "byBreed" }) | @Html.ActionLink("Sort By Type", "Index", new { sortBy = "byType" }) | @Html.ActionLink("Sort By Admission Date", "Index", new { sortBy = "byDateAdmitted" })</p>

  <ul class="list">
    @foreach (Animal animal in Model["sortBy"])
    {
      <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add an animal", "Create")</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

AnimalShelter.Solution/AnimalShelter/Views/Home/Index.cshtml
@{
  ViewBag.Title = "Home Page";
  Layout = "_Layout";
}

<h1>Welcome to our Animal Shelter!</h1>
<br>
<p>@Html.ActionLink("See all animals", "Index", "Animals")</p>

AnimalShelter.Solution/AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.Title - Animal Shelter</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Roboto&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="container">
    @RenderBody()
    </div>
  </body>
</html>